lock: add missing include after 68587e2920b5
src/lock.c:56:46: error: use of undeclared identifier 'S_IRUSR'
        int fd = open(filename, O_RDONLY | O_CREAT, S_IRUSR | S_IWUSR);
                                                    ^
src/lock.c:56:56: error: use of undeclared identifier 'S_IWUSR'
        int fd = open(filename, O_RDONLY | O_CREAT, S_IRUSR | S_IWUSR);
                                                              ^